# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

# on:
#   workflow_run:
#     workflows: ["Build and Push"]
#     types:
#       - completed

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pull image
        run: docker pull ashrash290/toggleanything:latest

      - name: Deploy image
        run: docker run -p 3000:3000 --env-file ./dev.env ashrash290/toggleanything:latest
